### ISSUE TITLE
Define "steno theory" earlier in the text

### ISSUE THREAD

**Issue by waldyrious** [morinted/plover_theory#3]
The word "theory" is used with a very specific meaning in this book, and appears both in the title and several times in the introduction, but it's only when one reaches the "What about other theories?" section that one starts getting a feel of what it actually means (and where the full expression "steno theory" appears for the first time).

As an absolute steno beginner, I think it would be helpful to somehow define this earlier, especially since the word is in the title of the book.

**Comment by panathea** [comment]
Great point, the book definitely needs some world-building in an
introduction.

**Comment by panathea** [comment]
I've revisited the [introduction](https://morinted.gitbooks.io/plover-theory/content/) and added more links to help the reader make sense of what is going on if this is somehow their first time hearing about steno.

I plan on adding more illustrations later (that will probably be quite late in the process, once I'm done most of the lessons)

**Comment by waldyrious** [comment]
Nice changes, and illustrations would be great, too. I've made a few edits to the introduction text and submitted them as PR #4 -- let me know what you think.
